// <auto-generated />
using BerrasBio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BerrasBio.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    partial class MoviesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BerrasBio.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Romantic",
                            MovieName = "Titanic"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Crime",
                            MovieName = "The Hateful Eight"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Biography",
                            MovieName = "Catch Me If You Can"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Horror",
                            MovieName = "The Conjuring"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Action",
                            MovieName = "Tenet"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Drama",
                            MovieName = "Min Pappa Marianne"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Comedy",
                            MovieName = "American Pie"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Thriller",
                            MovieName = "Parasit"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Romantic",
                            MovieName = "Mamma Mia!"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Sci-Fi",
                            MovieName = "Avengers"
                        },
                        new
                        {
                            Id = 11,
                            Genre = "Documentary",
                            MovieName = "Det Sociala Arvet"
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Horror",
                            MovieName = "The Conjuring 2"
                        },
                        new
                        {
                            Id = 13,
                            Genre = "Documentary",
                            MovieName = "Searching for Sugar Man"
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Thriller",
                            MovieName = "John Wick"
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Sci-Fi",
                            MovieName = "The Invisible Man"
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Drama",
                            MovieName = "Joker"
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Horror",
                            MovieName = "Get Out"
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Thriller",
                            MovieName = "The Revenant"
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Drama",
                            MovieName = "Manchester By The Sea"
                        },
                        new
                        {
                            Id = 20,
                            Genre = "Musical",
                            MovieName = "La La Land"
                        },
                        new
                        {
                            Id = 21,
                            Genre = "Drama",
                            MovieName = "The Big Short"
                        },
                        new
                        {
                            Id = 22,
                            Genre = "Family",
                            MovieName = "Toy Story"
                        },
                        new
                        {
                            Id = 23,
                            Genre = "Crime",
                            MovieName = "Three Billboards Outside Ebbing, Missouri"
                        },
                        new
                        {
                            Id = 24,
                            Genre = "Documentary",
                            MovieName = "Amy"
                        },
                        new
                        {
                            Id = 25,
                            Genre = "Action",
                            MovieName = "Gladiator"
                        },
                        new
                        {
                            Id = 26,
                            Genre = "Sci-Fi",
                            MovieName = "Lord Of The Rings"
                        },
                        new
                        {
                            Id = 27,
                            Genre = "Crime",
                            MovieName = "The Departed"
                        },
                        new
                        {
                            Id = 28,
                            Genre = "Drama",
                            MovieName = "Slumdog Millionaire"
                        },
                        new
                        {
                            Id = 29,
                            Genre = "Biography",
                            MovieName = "12 Years A Slave"
                        },
                        new
                        {
                            Id = 30,
                            Genre = "Comedy",
                            MovieName = "Forrest Gump"
                        });
                });

            modelBuilder.Entity("BerrasBio.Models.MovieDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenMovieStarts")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 73,
                            MovieName = "Titanic",
                            WhenMovieStarts = "15:30"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 12,
                            MovieName = "The Hateful Eight",
                            WhenMovieStarts = "20:00"
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 55,
                            MovieName = "Catch Me If You Can",
                            WhenMovieStarts = "12:00"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 23,
                            MovieName = "The Conjuring",
                            WhenMovieStarts = "21:30"
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 19,
                            MovieName = "Tenet",
                            WhenMovieStarts = "18:45"
                        },
                        new
                        {
                            Id = 6,
                            AvailableSeats = 45,
                            MovieName = "Min Pappa Marianne",
                            WhenMovieStarts = "19:00"
                        },
                        new
                        {
                            Id = 7,
                            AvailableSeats = 9,
                            MovieName = "American Pie",
                            WhenMovieStarts = "20:30"
                        },
                        new
                        {
                            Id = 8,
                            AvailableSeats = 4,
                            MovieName = "Parasit",
                            WhenMovieStarts = "22:15"
                        },
                        new
                        {
                            Id = 9,
                            AvailableSeats = 95,
                            MovieName = "Mamma Mia!",
                            WhenMovieStarts = "11:00"
                        },
                        new
                        {
                            Id = 10,
                            AvailableSeats = 34,
                            MovieName = "Avengers",
                            WhenMovieStarts = "18:30"
                        },
                        new
                        {
                            Id = 11,
                            AvailableSeats = 39,
                            MovieName = "Det Sociala Arvet",
                            WhenMovieStarts = "17:45"
                        },
                        new
                        {
                            Id = 12,
                            AvailableSeats = 10,
                            MovieName = "The Conjuring 2",
                            WhenMovieStarts = "22:00"
                        },
                        new
                        {
                            Id = 13,
                            AvailableSeats = 37,
                            MovieName = "Searching for Sugar Man",
                            WhenMovieStarts = "15:00"
                        },
                        new
                        {
                            Id = 14,
                            AvailableSeats = 5,
                            MovieName = "John Wick",
                            WhenMovieStarts = "20:00"
                        },
                        new
                        {
                            Id = 15,
                            AvailableSeats = 44,
                            MovieName = "The Invisible Man",
                            WhenMovieStarts = "19:15"
                        },
                        new
                        {
                            Id = 16,
                            AvailableSeats = 0,
                            MovieName = "Joker",
                            WhenMovieStarts = "21:00"
                        },
                        new
                        {
                            Id = 17,
                            AvailableSeats = 20,
                            MovieName = "Get Out",
                            WhenMovieStarts = "21:30"
                        },
                        new
                        {
                            Id = 18,
                            AvailableSeats = 69,
                            MovieName = "The Revenant",
                            WhenMovieStarts = "16:00"
                        },
                        new
                        {
                            Id = 19,
                            AvailableSeats = 47,
                            MovieName = "Manchester By The Sea",
                            WhenMovieStarts = "13:00"
                        },
                        new
                        {
                            Id = 20,
                            AvailableSeats = 18,
                            MovieName = "La La Land",
                            WhenMovieStarts = "14:45"
                        },
                        new
                        {
                            Id = 21,
                            AvailableSeats = 78,
                            MovieName = "The Big Short",
                            WhenMovieStarts = "17:00"
                        },
                        new
                        {
                            Id = 22,
                            AvailableSeats = 40,
                            MovieName = "Toy Story",
                            WhenMovieStarts = "13:30"
                        },
                        new
                        {
                            Id = 23,
                            AvailableSeats = 27,
                            MovieName = "Three Billboards Outside Ebbing, Missouri",
                            WhenMovieStarts = "18:30"
                        },
                        new
                        {
                            Id = 24,
                            AvailableSeats = 33,
                            MovieName = "Amy",
                            WhenMovieStarts = "19:00"
                        },
                        new
                        {
                            Id = 25,
                            AvailableSeats = 0,
                            MovieName = "Gladiator",
                            WhenMovieStarts = "20:30"
                        },
                        new
                        {
                            Id = 26,
                            AvailableSeats = 15,
                            MovieName = "Lord Of The Rings",
                            WhenMovieStarts = "18:00"
                        },
                        new
                        {
                            Id = 27,
                            AvailableSeats = 53,
                            MovieName = "The Departed",
                            WhenMovieStarts = "21:45"
                        },
                        new
                        {
                            Id = 28,
                            AvailableSeats = 73,
                            MovieName = "Slumdog Millionaire",
                            WhenMovieStarts = "17:00"
                        },
                        new
                        {
                            Id = 29,
                            AvailableSeats = 7,
                            MovieName = "12 Years A Slave",
                            WhenMovieStarts = "18:30"
                        },
                        new
                        {
                            Id = 30,
                            AvailableSeats = 29,
                            MovieName = "Forrest Gump",
                            WhenMovieStarts = "15:45"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
